// Package middlewares contains HTTP middlewares.
package middlewares

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"encoding/hex"
	"io"
	"log/slog"
	"net"
	"net/http"
	"runtime/debug"
	"strconv"
	"time"

	"github.com/z0rr0/inngen/web/limiter"
)

const (
	// HTTPRequestIDHeader is the header key for the request ID.
	HTTPRequestIDHeader = "X-Request-Id"

	// HTTPIPHeader is the header key for the IP address.
	HTTPIPHeader = "X-Forwarded-For"

	// requestIDLen is a length of generated request ID in bytes.
	requestIDLen = 16
	// requestIDPrefix is a prefix for request ID generated by the application.
	requestIDPrefix = "x-"
)

type ctxPrivateType string

// CtxSettingsType is the type of the database connection pool in the context.
type CtxSettingsType string

const (
	requestIDKey ctxPrivateType = "requestID"
)

// ErrorHandlingMiddleware handles panics and logs the error.
func ErrorHandlingMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		defer func(ctx context.Context) {
			if err := recover(); err != nil {
				requestID := ctx.Value(requestIDKey)
				slog.ErrorContext(ctx, "panic recovered",
					"error", err,
					"requestID", requestID,
					"stack", string(debug.Stack()),
				)
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
			}
		}(r.Context())
		next.ServeHTTP(w, r)
	})
}

func getHeader(r *http.Request, header string) string {
	if r == nil {
		return ""
	}

	return r.Header.Get(header)
}

// RequestID returns the request ID from the request headers.
func RequestID(r *http.Request) string {
	if requestID := getHeader(r, HTTPRequestIDHeader); requestID != "" {
		return requestID
	}

	return requestIDPrefix + generateRequestID()
}

// generateRequestID generates a new request ID.
// It uses requestIDLen bytes of random data or current nanoseconds timestamp as a fallback.
func generateRequestID() string {
	bytes := make([]byte, requestIDLen)
	_, err := io.ReadFull(rand.Reader, bytes)

	if err != nil {
		slog.Warn("failed to generate request ID", "error", err)
		return strconv.FormatInt(time.Now().UnixNano(), 16)
	}

	return hex.EncodeToString(bytes)
}

// LoggingMiddleware creates a middlewares that logs incoming requests and their duration.
func LoggingMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var (
			start     = time.Now()
			requestID = RequestID(r)
			ctx       = r.Context()
		)

		ctx = context.WithValue(ctx, requestIDKey, requestID)
		r = r.WithContext(ctx)

		slog.InfoContext(ctx, "request started",
			"requestID", requestID,
			"method", r.Method,
			"path", r.URL.Path,
			"remote_addr", r.RemoteAddr,
		)

		wrappedWriter := wrapResponseWriter(w)
		wrappedWriter.Header().Set("X-Request-ID", requestID)

		next.ServeHTTP(wrappedWriter, r)

		attrs := []any{
			slog.Int("status", wrappedWriter.Status()),
			slog.Int64("bytes", wrappedWriter.BytesWritten()),
			slog.String("requestID", requestID),
			slog.String("method", r.Method),
			slog.String("path", r.URL.Path),
			slog.String("remoteAddr", r.RemoteAddr),
			slog.Duration("duration", time.Since(start)),
		}

		if r.URL.RawQuery != "" {
			attrs = append(attrs, slog.String("query", r.URL.RawQuery))
		}

		switch {
		case wrappedWriter.Status() >= http.StatusInternalServerError:
			slog.ErrorContext(ctx, "request completed with server error", attrs...)
		case wrappedWriter.Status() >= http.StatusBadRequest:
			slog.WarnContext(ctx, "request completed with client error", attrs...)
		default:
			slog.InfoContext(ctx, "request completed", attrs...)
		}
	})
}

// RateLimiterMiddleware is a middlewares that limits the rate of incoming requests.
// It adds the IP to the request context, if the rate limiter is not reached.
func RateLimiterMiddleware(next http.Handler, rateLimiter *limiter.RateLimiter[string]) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		ipAddr := getHeader(r, HTTPIPHeader)

		if ipAddr == "" {
			host, _, err := net.SplitHostPort(r.RemoteAddr)
			if err != nil {
				slog.WarnContext(ctx, "failed to parse remote address", "error", err)
				host = r.RemoteAddr
			}
			ipAddr = host
		}

		if rateLimiter == nil {
			next.ServeHTTP(w, r) // no rate limiting
			return
		}

		if bucket := rateLimiter.GetBucket(ipAddr); bucket != nil && !bucket.Allow() {
			slog.WarnContext(ctx, "rate limit exceeded", "IP", ipAddr)
			http.Error(w, "Too Many Requests", http.StatusTooManyRequests)
			return
		}

		next.ServeHTTP(w, r)
	})
}

// BasicAuthMiddleware is a middlewares that checks for basic authentication.
// Expected it will be called after RateLimiterMiddleware.
func BasicAuthMiddleware(next http.Handler, users map[string]string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if users == nil {
			next.ServeHTTP(w, r) // no authentication
			return
		}

		username, password, ok := r.BasicAuth()
		if !ok {
			w.Header().Set("WWW-Authenticate", `Basic realm="Restricted"`)
			http.Error(w, "Unauthorized", http.StatusUnauthorized)
			return
		}

		// anyway compare passwords to avoid timing attacks
		if expected := []byte(users[username]); !hmac.Equal([]byte(password), expected) {
			slog.Warn("invalid credentials", "username", username)
			w.Header().Set("WWW-Authenticate", `Basic realm="Restricted"`)
			http.Error(w, "Unauthorized", http.StatusUnauthorized)
			return
		}

		next.ServeHTTP(w, r)
	})
}
