# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.25.3"
          check-latest: true

      - name: Check Go version
        run: go version

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          args: --config=golangci.yml --issues-exit-code=0

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          install-go: false
          min-go-version: "1.25"

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: "1.25"
          go-package: ./...
